### ISSUE TITLE
Speed up destroy command

### ISSUE THREAD

**Issue by desecho** [lxdock/lxdock#30] opened 2017-02-24 19:40 UTC
Don't attempt to stop containers when destroying them to gain speed.

**Comment by hsoft** [comment] 2017-02-24 19:46
Maybe that your issue in #31 is causing you to wish we would directly destroy containers? On my machine, containers are generally pretty quick to stop. Maybe there's something wrong with your configuration?

**Comment by desecho** [comment] 2017-02-27 19:16
How can I find out what is the problem with my configuration? What should I look into?

**Comment by hsoft** [comment] 2017-02-27 19:42
I'm not quite sure. I once had very slow startup/shutdown times, but that was because I had a completely non-functional setup. If you're in the same situation I was in, your containers will not get an IPv4 address.

Anyway, what are we talking about exactly? 5 seconds? one minutes? how long does it take for your containers to shut down? It should generally be less than 5 seconds, 10 seconds max.

**Comment by desecho** [comment] 2017-02-27 20:02
Startup time is fine. It looks like everything is fine with IPv4 address. Generally it forces a container to stop and that takes 30 seconds, however sometimes it succeeds in stopping the container and in that case it takes 20 seconds.

**Comment by ellmetha** [comment] 2017-02-28 20:53
@desecho could you copy paste the output of `lxc stop [container_id]`?

**Comment by desecho** [comment] 2017-02-28 22:20
There is no output for `lxc stop [container_id]`. It just hangs. However I found out that it shutdowns fine on Ubuntu 14.04 containers and it fails on Ubuntu 16.04 containers.
Here's the output of init 0 after connecting through shell:
```
Warning! D-Bus connection terminated.
Failed to wait for response: Connection reset by peer
Failed to open /dev/initctl: No such device or address
Failed to talk to init daemon.
```

**Comment by hsoft** [comment] 2017-03-05 01:12
@desecho does it work better if you make the container privileged?

**Comment by desecho** [comment] 2017-03-20 16:50
@hsoft Yes, if a container is privileged it works fine.

**Comment by hsoft** [comment] 2017-07-10 23:07
It took me a long time to respond, but I'm in a "cleanup" mood. If the issue is resolved in privileged mode, it means that your destroy command is slow because your container's init sequence is broken. The issue isn't, then about speeding up the destroy command, but rather to make the container work at all.

**Closed by hsoft** 2017-07-10 23:07 UTC
